services:
  db:
    image: postgres:16
    container_name: financial_app_db
    env_file:
      - ./core-api/.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  core-api:
    build:
      context: ./core-api
      dockerfile: core-api.dockerfile
    container_name: financial_app_core-api
    depends_on:
      - db
    env_file:
      - ./core-api/.env
    ports:
      - "${CORE_PORT}:${CORE_PORT}"
    volumes:
      - ./core-api:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  agent-api:
    build:
      context: ./agent-api
      dockerfile: agent-api.dockerfile
    container_name: financial_app_agent-api
    depends_on:
      - db
    env_file:
      - ./agent-api/.env
    ports:
      - "${AGENT_PORT}:${AGENT_PORT}"
    volumes:
      - ./agent-api:/app
      - /app/venv
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      [
        "fastapi",
        "dev",
        "main.py",
        "--port",
        "${AGENT_PORT}",
        "--host",
        "0.0.0.0",
      ]
volumes:
  postgres_data:
