services:
  db:
    image: postgres:16
    container_name: financial_app_db
    env_file:
      - ./core-api/.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  core-api:
    build:
      context: ./core-api
      dockerfile: core-api.dockerfile
    container_name: financial_app_core-api
    depends_on:
      - db
    env_file:
      - ./core-api/.env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./core-api:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  postgres_data: