services:
  db:
    image: postgres:16
    container_name: financial_app_db
    env_file:
      - ./backend/.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    container_name: financial_app_backend
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  postgres_data: