services:
  db:
    image: postgres:16
    container_name: financial_app_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    container_name: financial_app_backend
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    container_name: financial_app_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "start"]

volumes:
  postgres_data:
